apiVersion: apps/v1
kind: Deployment
metadata:
  name: badgerodon-www
  labels:
    app: badgerodon-www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: badgerodon-www
  template:
    metadata:
      labels:
        app: badgerodon-www
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: badgerodon-www
        image: gcr.io/doxsey-1/badgerodon-www:latest
        ports:
        - containerPort: 9001
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"

---

kind: Service
apiVersion: v1
metadata:
  name: badgerodon-www
spec:
  selector:
    app: badgerodon-www
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001


---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: badgerodon-com
  namespace: default
spec:
  secretName: badgerodon-com-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: '*.badgerodon.com'
  dnsNames:
  - badgerodon.com
  acme:
    config:
    - dns01:
        provider: cf-dns
      domains:
      - '*.badgerodon.com'
      - badgerodon.com