apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: doxsey-www
  labels:
    app: doxsey-www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doxsey-www
  template:
    metadata:
      labels:
        app: doxsey-www
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: doxsey-www
          image: quay.io/calebdoxsey/www:v1.4.0
          ports:
            - containerPort: 9002
          resources:
            requests:
              cpu: 0
            limits:
              memory: "50Mi"
              cpu: "100m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: doxsey-www-next
  labels:
    app: doxsey-www-next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doxsey-www-next
  template:
    metadata:
      labels:
        app: doxsey-www-next
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: doxsey-www
          image: quay.io/calebdoxsey/www:v1.4.0
          ports:
            - containerPort: 9002
          resources:
            requests:
              cpu: 0
            limits:
              memory: "50Mi"
              cpu: "100m"

---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: doxsey-www
spec:
  selector:
    app: doxsey-www
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002

---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: doxsey-www-next
spec:
  selector:
    app: doxsey-www-next
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: doxsey-www
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - "*.doxsey.net"
      secretName: doxsey-net-tls
  rules:
    - host: www.doxsey.net
      http:
        paths:
          - path: /
            backend:
              serviceName: doxsey-www
              servicePort: 9002
    - host: next.doxsey.net
      http:
        paths:
          - path: /
            backend:
              serviceName: doxsey-www-next
              servicePort: 9002

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: doxsey-net
  namespace: default
spec:
  secretName: doxsey-net-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: "*.doxsey.net"
  dnsNames:
    - doxsey.net
  acme:
    config:
      - dns01:
          provider: cf-dns
        domains:
          - "*.doxsey.net"
          - doxsey.net
