kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: nginx
  labels:
    name: nginx
    app: nginx
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        name: nginx
        app: nginx
      annotations:
        config-version: "9"
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 0
      containers:
      - image: nginx:1.15.3-alpine
        name: nginx
        resources:
          limits:
            cpu: "100m"
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        volumeMounts:
        - name: "config"
          mountPath: "/etc/nginx"
        - name: badgerodon-com-tls
          mountPath: "/etc/tls/badgerodon-com"
        - name: doxsey-net-tls
          mountPath: "/etc/tls/doxsey-net"
        - name: rtctunnel-com-tls
          mountPath: "/etc/tls/rtctunnel-com"
      volumes:
      - name: config
        configMap:
          name: nginx-conf
      - name: badgerodon-com-tls
        secret:
          secretName: badgerodon-com-tls
      - name: doxsey-net-tls
        secret:
          secretName: doxsey-net-tls
      - name: rtctunnel-com-tls
        secret:
          secretName: rtctunnel-com-tls

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes 1;
    error_log /dev/stdout info;

    events {
      worker_connections 10;
    }

    http {
      access_log /dev/stdout;

      server {
        listen 80;
        listen 443 ssl;
        server_name *.badgerodon.com;
        ssl_certificate     /etc/tls/badgerodon-com/tls.crt;
        ssl_certificate_key /etc/tls/badgerodon-com/tls.key;

        location / {
          proxy_pass http://badgerodon-www.default.svc.cluster.local:9001;
        }
      }

      server {
        listen 80;
        listen 443 ssl;
        server_name *.doxsey.net;
        ssl_certificate     /etc/tls/doxsey-net/tls.crt;
        ssl_certificate_key /etc/tls/doxsey-net/tls.key;

        location / {
          proxy_pass http://doxsey-www.default.svc.cluster.local:9002;
        }
      }

      server {
        listen 80;
        listen 443 ssl;
        server_name next.doxsey.net;
        ssl_certificate     /etc/tls/doxsey-net/tls.crt;
        ssl_certificate_key /etc/tls/doxsey-net/tls.key;

        location / {
          proxy_pass http://doxsey-www-next.default.svc.cluster.local:9002;
        }
      }

      server {
        listen 80;
        listen 443 ssl;
        server_name operator.rtctunnel.com;
        ssl_certificate     /etc/tls/rtctunnel-com/tls.crt;
        ssl_certificate_key /etc/tls/rtctunnel-com/tls.key;

        location / {
          proxy_pass http://rtctunnel-operator.default.svc.cluster.local:9100;
        }
      }
    }
