apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-connector
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: node-connector
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: node-connector-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-connector
subjects:
- kind: ServiceAccount
  name: node-connector
  namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-connector
  labels:
    app: node-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-connector
  template:
    metadata:
      labels:
        app: node-connector
    spec:
      serviceAccountName: node-connector
      containers:
      - name: node-connector
        image: gcr.io/doxsey-1/kubernetes-external-dns-node-connector
        args:
        - --dns-name=kubernetes.doxsey.net
        ports:
        - name: http
          containerPort: 8080
          hostPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: node-connector
spec:
  selector:
    app: node-connector
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080